org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true

# This newDsl flag was added by the Flutter template
android.newDsl=false

# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# Disable Kotlin incremental compilation.
# Prevents cross-drive cache path errors when the project
# is located on D: and the Pub cache is located on C:.
kotlin.incremental=false